language: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "markesz7"
    
script:
  - sonar-scanner
  - mvn clean package

after_success:
  - test $TRAVIS_BRANCH = "main" && test $TRAVIS_PULL_REQUEST = "false" &&
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD &&
    docker-compose build &&
    docker push markesz/webstore-devops

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  on: main
  app: webstore-devops
