language: java

addons:
  sonarcloud:
    organization: "markesz7"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Markesz7_webstore-devops

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  on: main
