language: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "markesz7"
    
script:
  - mvn clean package

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker-compose build
  - docker push markesz/webstore-devops

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  on: main
  app: webstore-devops
