language: java
jdk: openjdk11
services:
  - docker

addons:
  sonarcloud:
    organization: "markesz7"
    
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Markesz7_webstore-devops
  - mvn package -Dmaven.test.skip

after_success:
  - test $TRAVIS_BRANCH = "main" && test $TRAVIS_PULL_REQUEST = "false" &&
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
    docker-compose build &&
    docker push markesz/webstore-devops

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  on: 
    branch: main
    repo: Markesz7/webstore-devops
  app: webstore-devops
